### ISSUE TITLE
Debian 13 & libatlas-base-dev

### ISSUE THREAD

**Issue by AlatusAles** [Frix-x/klippain-shaketune#261]
### K-Shake&Tune module branch

- [x] I confirm using the main branch

### Version

Not use

### Describe the bug and expected behavior

Error: Package 'libatlas-base-dev' has no installation candidate

**Comment by Benik3** [comment]
It looks like libatlas is obsolete for a long time and the project should be moved to newer alternative.
Because of this, libatlas was removed in Debian Trixie :/
https://github.com/numpy/numpy/issues/29108

Klipper already moved to libopenblas-dev with it's resonance masuring.
Also nump<1.26 is no longer supported in Trixie, but Klipper loosk working fine with version 2.4
https://klipper.discourse.group/t/debian-trixie-deprecated-packages-in-measuring-resonances-dependencies/24955

**Comment by Benik3** [comment]
It looks like libatlas is really not needed.
But problem is with the Python 3.13. Not only numpy is not supported (but 1.6.4 can be compiled, which is still problematic for me on RPi Zero 2), but scipy 1.11 is even not possible to build on Trixie/Python 3.13.
I tried to install actual version of the python packages, but when I tried to run axis shaping, it fails in the computation stage.
EDIT: the problem is not with numpy/scipy, but with incompatibility with new Klipper...

**Comment by Legot** [comment]
Not sure why it hasn't been merged yet, but there was a compatibility fix in December that fixes the dependancy issues. You can also modify the requirements file from the main branch to do something simmilar. Just run these commands on your klipper host.
```bash
cd ~
sudo rm -r klippain_shaketune
git clone https://github.com/Frix-x/klippain-shaketune/ -b compat-dec2025
mv klippain-shaketune klippain_shaketune
./klippain_shaketune/install.sh
```

**Comment by lucaspbz** [comment]
> Not sure why it hasn't been merged yet, but there was a compatibility fix in December that fixes the dependancy issues. You can also modify the requirements file from the main branch to do something simmilar. Just run these commands on your klipper host.
> 
> cd ~
> sudo rm -r klippain_shaketune
> git clone https://github.com/Frix-x/klippain-shaketune/ -b compat-dec2025
> mv klippain-shaketune klippain_shaketune
> ./klippain_shaketune/install.sh

worked for me!

**Comment by Benik3** [comment]
It doesn't work for me, but it fails with different error:
```
Error while generating the graphs: x and y must have same first dimension, but have shapes (124,) and (1000,)
None
```
Also it installs PyWavelets 1.6.0, but for Python 3.13 version >=1.7.0 should be used.
Same error is outputted also with latest version 1.9.0, so it's not caused by this.

Overall I don't see a reason to have exact version in the requirements.
Instead in my opinion would by better to have e.g. numpy~=2.2.0, so latest version of 2.2.x will be installed. These version are just bug fixes and it doesn't contain breaking compatibility changes with actual code.

Also the packages are installed into the main klippy environment, so some forced version in theory can break some functionality of the klipper itself, when the version is changed for some already installed and required package...

**Comment by cha0stype** [comment]
@Benik3 The error you're getting is due to a breaking change in one of the recent versions of Klipper, see https://github.com/Frix-x/klippain-shaketune/issues/259

Klipper changed some of it's data generation, I manged to fix it, but it needs more testing. I'll make a pull request in the next few days.

**Comment by Benik3** [comment]
Yeah, I read it in this issue.
Let me know when you will have the pull request ready, I will test it :)

**Comment by Frix-x** [comment]
Hi :)
I'm just back from some holiday and will work on definitely fixing this now.

> Not sure why it hasn't been merged yet, but there was a compatibility fix in December that fixes the dependancy issues. 

This is because I wanted to release a full version with both fixes at the same time (this one for trixie compatibility that is known to be working and the one for the Klipper breaking change). However the second one is only fixed partially apparently and it's the error @Benik3 hit at the end about x and y dimensions not matching. I made the fix with Kalico in mind thinking it would work correctly for Klipper as well and was waiting for feedback from my tester group. I will fix it quickly and let you know when the branch is ready :)

**Comment by Benik3** [comment]
Hi :)
Thank you, I hope that you had a good holiday :)
I will be glad to test the fixes, but I found, that Klipper itself has problems with Trixie 13 and MPU9250/6500 :/
https://klipper.discourse.group/t/mpu9250-6500-high-noise-on-debian-13-trixie/25457/10

**Comment by Frix-x** [comment]
I just pushed the improved fix on the compat-dec2025 branch. So if you are already on this branch, just pull the latest commits and let me know if it's correctly working!

I'll have a look at your link, that's something that I'm not aware of yet, thanks for sharing

**Comment by Frix-x** [comment]
Merged in develop now

**Comment by Benik3** [comment]
Looks working fine, thanks :)
Just one small thing, when I did update on Bullseye (Python 3.9.4), i got this error:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.11.4 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.0.2 which is incompatible.`
What I understand, scipy is not required anymore, so I uninstalled it manually from the klippy-env.

**Comment by lucaspbz** [comment]
I have pulled the develop branch and rerun the install script. I still have the "Detected axes_map: unable to determine it correctly!". Is this expected to be fixed? Or is that something else?

**Comment by Benik3** [comment]
It looks like the changes broke compatibility with old Klipper (tested with v0.13.0-403-gb4c7cf4a3)
`Error while generating the graphs: boolean index did not match indexed array along axis 0; size of axis is 169 but size of corresponding boolean axis is 1025
None`

**Comment by Kabbone** [comment]
> It looks like the changes broke compatibility with old Klipper (tested with v0.13.0-403-gb4c7cf4a3) `Error while generating the graphs: boolean index did not match indexed array along axis 0; size of axis is 169 but size of corresponding boolean axis is 1025 None`

Same problem on newest Kalico

**Comment by Frix-x** [comment]
Can you share your full klippy.log please?

 A few people run into this issue but I can't replicate it on my side so I will need a bit more info to be able to fix it. And that's why develop branch is not released yet...

**Comment by Benik3** [comment]
[klippy(9).log](https://github.com/user-attachments/files/24554176/klippy.9.log)
But there is no error in it (even not this one).

**Comment by Frix-x** [comment]
Ok, I was able to replicate it by using the exact same version of Klipper you have and already pushed a fix in the develop branch. So now it should be good for everyone running older Klipper, new Klipper or Kalico!
